/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package item;

import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import common.Checknull;
import common.SystemData;
import common.TbView;
import common.db;
import java.awt.Color;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author udesh
 */
public class add_update extends javax.swing.JFrame {

    /**
     * Creates new form add_update
     */
    public add_update() {
        initComponents();
        screensize();
          TbView.tableSettings(jTable1);
           jscole1.setVisible(false);
            jScrollPane4.setVisible(false);
            loadname();
    }
     boolean stop =false;
private void screensize() {
      
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtitmn = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        list2 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btndash = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtitna = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtde = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        txtSup = new javax.swing.JTextField();
        jscole1 = new javax.swing.JScrollPane();
        list3 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1840, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 100, -1, -1));

        txtitmn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtitmn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtitmnActionPerformed(evt);
            }
        });
        txtitmn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtitmnKeyReleased(evt);
            }
        });
        getContentPane().add(txtitmn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 80, 240, 30));

        list2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list2MouseClicked(evt);
            }
        });
        list2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                list2KeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(list2);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 110, 240, 90));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Seach By Item");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, 210, 30));

        jLabel4.setBackground(new java.awt.Color(0, 0, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Upadate / Delete_Item");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 1050, 70));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("  Gamdora Distriburtors");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        jLabel3.setBackground(new java.awt.Color(0, 102, 0));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 60));

        btndash.setBackground(new java.awt.Color(0, 0, 51));
        btndash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndash.setForeground(new java.awt.Color(255, 255, 255));
        btndash.setText("Back");
        btndash.setToolTipText("");
        btndash.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btndash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndashMouseExited(evt);
            }
        });
        btndash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndashActionPerformed(evt);
            }
        });
        getContentPane().add(btndash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 250, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("setting");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 70, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 1220));

        jLabel5.setBackground(new java.awt.Color(0, 0, 51));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 1220));

        txtitna.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtitna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtitnaActionPerformed(evt);
            }
        });
        getContentPane().add(txtitna, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 240, 30));

        txtde.setColumns(20);
        txtde.setRows(5);
        txtde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdeKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtde);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 240, 140));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Description");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 120, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Suplayer");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 120, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Item Name");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 120, 30));

        jButton8.setBackground(new java.awt.Color(0, 0, 102));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 600, 180, 30));

        jButton5.setBackground(new java.awt.Color(0, 0, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 600, 180, 30));
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, -1, -1));

        txtSup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupActionPerformed(evt);
            }
        });
        txtSup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupKeyReleased(evt);
            }
        });
        getContentPane().add(txtSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 240, -1));

        list3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list3MouseClicked(evt);
            }
        });
        list3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                list3KeyReleased(evt);
            }
        });
        jscole1.setViewportView(list3);

        getContentPane().add(jscole1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 240, 20));

        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item No", "Item Name", "Suplayer", "Description", "register_date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 660, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashMouseEntered
        btndash.setBackground(Color.BLUE);
    }//GEN-LAST:event_btndashMouseEntered

    private void btndashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashMouseExited
        btndash.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_btndashMouseExited

    private void btndashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashActionPerformed
                       new Viwe_item().setVisible(true);

    }//GEN-LAST:event_btndashActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtitnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtitnaActionPerformed
               Checknull.checkNull(txtitmn, "item", txtSup);

    }//GEN-LAST:event_txtitnaActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         try {
             stop=false;
                
              String itemId = txtitmn.getText().toUpperCase();
             String name= txtitna.getText().toUpperCase();
            String suplayer= txtSup.getText().toUpperCase();
            String des= txtde.getText().toUpperCase();
           String registerDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
            db.iud("UPDATE item SET item_id='"+itemId+"',name='"+name+"',suplayer='"+suplayer+"',description='"+des+"',employee_id='"+SystemData.getEmployee()+"',register_date='"+registerDate+"' where item_id='"+txtitmn.getText()+"'");
            JOptionPane.showMessageDialog(this, ""+txtitmn.getText()+" IS Successfully update!!");
            
            
             try {
            ResultSet rs = db.serch("SELECT * FROM item WHERE stat=1");
         DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
         dtm.setRowCount(0);
         while(rs.next()){
                java.util.Vector v =new java.util.Vector ();
              v.add(rs.getString("item_id"));
         v.add(rs.getString("name"));
          v.add(rs.getString("suplayer"));
            v.add(rs.getString("description"));
             v.add(rs.getString("register_date"));
            dtm.addRow(v);
         }
        } catch (Exception e) {
            e.printStackTrace();
        }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
       
           
            txtitmn.setText(null);
           txtitna.setText(null);
           txtSup.setText(null);
           txtde.setText(null);
             
     
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       try {
         
          
          
        db.iud("update item set stat='"+"0"+"' where item_id='"+txtitmn.getText()+"'");
          JOptionPane.showMessageDialog(this, " "+ txtitmn.getText()+" Item is Remove");
         

        } catch (Exception e) {
            e.printStackTrace();
        }
              txtitmn.setText(null);
           txtitna.setText(null);
           txtSup.setText(null);
           txtde.setText(null);
           loadname();
          
               
           
         
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupActionPerformed
                Checknull.checkNull(txtSup, "suplayer", txtSup);

    }//GEN-LAST:event_txtSupActionPerformed

    private void txtSupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupKeyReleased
        try{
            if(!txtSup.getText().trim().equals("")){
                if(txtSup.getText().toUpperCase().contains("S")){
                    ResultSet rs=  db.serch("SELECT * FROM  suplayer WHERE stat=1 AND suplayer_id  LIKE '"+txtSup.getText().toUpperCase()+"%'");
                    java.util.Vector v = new java.util.Vector();
                    jscole1.setVisible(false);
                    while(rs.next()){
                        jscole1.setVisible(true);
                        v.add(rs.getString("suplayer_id")+"-"+rs.getString("name"));
                    }
                    list3.setListData(v);
                }else{
                    ResultSet rs=  db.serch("SELECT * FROM suplayer WHERE stat=1 AND name LIKE '"+txtSup.getText().toUpperCase()+"%'");
                    java.util.Vector v = new java.util.Vector();
                    jscole1.setVisible(false);
                    while(rs.next()){
                        jscole1.setVisible(true);
                        v.add(rs.getString("suplayer_id")+"-"+rs.getString("name"));
                    }
                    list3.setListData(v);
                }
            }else{
                jscole1.setVisible(false);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtSupKeyReleased

    private void list3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list3MouseClicked
        if(evt.getClickCount()==2){
            txtSup.setText(list3.getSelectedValue().split("-")[0]);

            jscole1.setVisible(false);

        }
    }//GEN-LAST:event_list3MouseClicked

    private void list3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_list3KeyReleased

    }//GEN-LAST:event_list3KeyReleased

    private void txtitmnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtitmnActionPerformed
        seachem();
    }//GEN-LAST:event_txtitmnActionPerformed

    private void txtitmnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitmnKeyReleased
       try{
            if(!txtitmn.getText().trim().equals("")){
            if(txtitmn.getText().toUpperCase().contains("I")){
                ResultSet rs=  db.serch("SELECT * FROM item WHERE stat=1 AND item_id  LIKE '"+txtitmn.getText().toUpperCase()+"%'");
                java.util.Vector v = new java.util.Vector();
                       jScrollPane4.setVisible(false);
                while(rs.next()){
                     jScrollPane4.setVisible(true);
                    v.add(rs.getString("item_id")+"-"+rs.getString("name"));
                }
                list2.setListData(v);
            }else{
                ResultSet rs=  db.serch("SELECT * FROM item WHERE stat=1 AND name LIKE '"+txtitmn.getText().toUpperCase()+"%'");
                java.util.Vector v = new java.util.Vector();
                 jScrollPane4.setVisible(false);
                while(rs.next()){
                    jScrollPane4.setVisible(true);
                    v.add(rs.getString("item_id")+"-"+rs.getString("name"));  
                }
                list2.setListData(v);
            }
            }else{
             jScrollPane4.setVisible(false);
            }
}catch(Exception e){
e.printStackTrace();
}
    }//GEN-LAST:event_txtitmnKeyReleased

    private void list2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list2MouseClicked
        if(evt.getClickCount()==2){
            txtitmn.setText(list2.getSelectedValue().split("-")[0]);

            seachem();
            loadText2();
            jScrollPane4.setVisible(false);

        }
    }//GEN-LAST:event_list2MouseClicked

    private void list2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_list2KeyReleased
//        
    }//GEN-LAST:event_list2KeyReleased

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        loadText2();
    }//GEN-LAST:event_jTable1MousePressed

    private void txtdeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdeKeyTyped
      if(txtde.getText().length()==10){
          evt.consume();
         }
    }//GEN-LAST:event_txtdeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
          UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndash;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane jscole1;
    private javax.swing.JList<String> list2;
    private javax.swing.JList<String> list3;
    private javax.swing.JTextField txtSup;
    private javax.swing.JTextArea txtde;
    private javax.swing.JTextField txtitmn;
    private javax.swing.JTextField txtitna;
    // End of variables declaration//GEN-END:variables

    private void seachem() {
         try {
     ResultSet rs = db.serch("select * from item where item_id='"+txtitmn.getText()+" AND stat=1'");
            stop=true;
            //bc.setVisible(true);
            //bu.setVisible(true);
         DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
         dtm.setRowCount(0);
         while(rs.next()){
             
         java.util.Vector v =new java.util.Vector ();
           v.add(rs.getString("item_id"));
         v.add(rs.getString("name"));
          v.add(rs.getString("suplayer"));
            v.add(rs.getString("description"));
             v.add(rs.getString("register_date"));
            dtm.addRow(v);
                
         }
        // txtSearch.setText(null);
        } catch (Exception e) {
            e.printStackTrace();
        }
         
    }

    private void loadText2() {
         try {
                        
            ResultSet serch = db.serch("SELECT * FROM item WHERE item_id='"+txtitmn.getText().toUpperCase()+"'");
            
            if(serch.next()){
                
           txtitmn.setText(serch.getString("item_id"));
           txtitna.setText(serch.getString("name"));
           txtSup.setText(serch.getString("suplayer"));
           txtde.setText(serch.getString("description"));
         
            }else{
            
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadname() {
        try {
            ResultSet rs = db.serch("select * from item where stat =1");
            DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
             while(rs.next()){
            
         java.util.Vector v =new java.util.Vector ();
         v.add(rs.getString("item_id"));
         v.add(rs.getString("name"));
          v.add(rs.getString("suplayer"));
            v.add(rs.getString("description"));
             v.add(rs.getString("register_date"));
            dtm.addRow(v);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

