/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package suplayer;

import customer.*;
import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import common.Checknull;
import common.SystemData;
import common.TbView;
import common.db;
import java.awt.Color;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author udesh
 */
public class updateSuplayer extends javax.swing.JFrame {

    /**
     * Creates new form Update_customer
     */
    public updateSuplayer() {
        initComponents();
        screensize();
          TbView.tableSettings(jTable1);
          jScrollPane2.setVisible(false);
          loadcustomer();
    }
 private void screensize() {
      
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    
}
 boolean stop =false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList<>();
        txtSearch = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btndash = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtnic1 = new javax.swing.JTextField();
        txtfn = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtln = new javax.swing.JTextField();
        txtca = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        up = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        txtea = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1840, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 1209, -1, -1));

        list1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list1MouseClicked(evt);
            }
        });
        list1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                list1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(list1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 110, 240, 90));

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 80, 240, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(" Search ");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 100, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("  Gamdora Distriburtors");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        jLabel3.setBackground(new java.awt.Color(0, 102, 0));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 60));

        btndash.setBackground(new java.awt.Color(0, 0, 51));
        btndash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndash.setForeground(new java.awt.Color(255, 255, 255));
        btndash.setText("Back");
        btndash.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btndash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndashMouseExited(evt);
            }
        });
        btndash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndashActionPerformed(evt);
            }
        });
        getContentPane().add(btndash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 1220));

        jLabel4.setBackground(new java.awt.Color(0, 0, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Suplayer  Update");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 1050, 70));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("NIC");
        jLabel23.setToolTipText("");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 150, 30));

        txtnic1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtnic1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnic1MouseClicked(evt);
            }
        });
        txtnic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnic1ActionPerformed(evt);
            }
        });
        txtnic1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnic1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnic1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnic1KeyTyped(evt);
            }
        });
        getContentPane().add(txtnic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 240, 30));

        txtfn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtfn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnActionPerformed(evt);
            }
        });
        txtfn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfnKeyTyped(evt);
            }
        });
        getContentPane().add(txtfn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 240, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 150, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Company");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 130, 30));

        txtln.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnActionPerformed(evt);
            }
        });
        txtln.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlnKeyTyped(evt);
            }
        });
        getContentPane().add(txtln, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 240, 30));

        txtca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcaActionPerformed(evt);
            }
        });
        txtca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcaKeyTyped(evt);
            }
        });
        getContentPane().add(txtca, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 240, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Contact NO");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 150, 30));

        up.setBackground(new java.awt.Color(0, 0, 102));
        up.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        up.setForeground(new java.awt.Color(255, 255, 255));
        up.setText("UpDate");
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        getContentPane().add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 580, 180, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("setting");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 70, 30));

        jTable1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Suplayer ID", "NIC", "Name", "Company", "Phone", "Email", "Register Date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 660, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Email address");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 150, 30));

        txtea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteaActionPerformed(evt);
            }
        });
        getContentPane().add(txtea, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 240, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashMouseEntered
        btndash.setBackground(Color.BLUE);
    }//GEN-LAST:event_btndashMouseEntered

    private void btndashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashMouseExited
        btndash.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_btndashMouseExited

    private void btndashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashActionPerformed
        new suplayer_menegment().setVisible(true);
    }//GEN-LAST:event_btndashActionPerformed

    private void txtnic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnic1ActionPerformed
             Checknull.checkNull(txtnic1, "nic", txtfn);
    }//GEN-LAST:event_txtnic1ActionPerformed

    private void txtfnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnActionPerformed
                Checknull.checkNull(txtfn, "Fname", txtln);
    }//GEN-LAST:event_txtfnActionPerformed

    private void txtlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnActionPerformed
               Checknull.checkNull(txtln, "Lname", txtln);
    }//GEN-LAST:event_txtlnActionPerformed

    private void txtcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcaActionPerformed
               Checknull.checkNull(txtca, "contact", txtea);
    }//GEN-LAST:event_txtcaActionPerformed

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
          try {
             stop=false;
                
              String suplayerId = txtSearch.getText().toUpperCase();
             String nic= txtnic1.getText().toUpperCase();
            String name= txtfn.getText().toUpperCase();
            String company= txtln.getText().toUpperCase();
            String contact =txtca.getText().toUpperCase();
             String email =txtea.getText().toUpperCase();
           String registerDate = new SimpleDateFormat("yyyy-MM-dd ").format(new Date());
            db.iud("UPDATE suplayer SET suplayer_id='"+suplayerId+"',nic='"+nic+"',name='"+name+"',company='"+company+"',phone='"+contact+"',email='"+email+"',register_date='"+registerDate+"' where suplayer_id='"+txtSearch.getText()+"'");
            JOptionPane.showMessageDialog(this, ""+txtSearch.getText()+" IS Successfully update!!");
            try {
            ResultSet rs = db.serch("select * from suplayer ");
            DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
          while(rs.next()){
         java.util.Vector v =new java.util.Vector ();
         v.add(rs.getString("suplayer_id"));
         v.add(rs.getString("nic"));
          v.add(rs.getString("name"));
            v.add(rs.getString("company"));
         v.add(rs.getString("phone"));
         v.add(rs.getString("email"));
         v.add(rs.getString("register_date"));
         dtm.addRow(v);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
            
             
            
        } catch (Exception e) {
            e.printStackTrace();
        }
       
            txtSearch.setText(null);
           txtnic1.setText(null);
           txtfn.setText(null);
           txtln.setText(null);
           txtea.setText(null);
           txtca.setText(null);
             
             
             
           
    }//GEN-LAST:event_upActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteaActionPerformed
                Checknull.checkNull(txtea, "email", txtea);
                up.grabFocus();
    }//GEN-LAST:event_txteaActionPerformed

    private void list1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list1MouseClicked
        if(evt.getClickCount()==2){
            txtSearch.setText(list1.getSelectedValue().split("-")[0]);
            seachem();
            loadText2();
            jScrollPane2.setVisible(false);

        }
    }//GEN-LAST:event_list1MouseClicked

    private void list1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_list1KeyReleased

    }//GEN-LAST:event_list1KeyReleased

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
         Checknull.checkNull(txtSearch, "email", txtnic1);
        seachem();
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
      try{
            if(!txtSearch.getText().trim().equals("")){
            if(txtSearch.getText().toUpperCase().contains("S")){
                ResultSet rs=  db.serch("SELECT * FROM suplayer WHERE stat=1 AND suplayer_id  LIKE '"+txtSearch.getText().toUpperCase()+"%'");
                java.util.Vector v = new java.util.Vector();
                       jScrollPane2.setVisible(false);
                while(rs.next()){
                     jScrollPane2.setVisible(true);
                    v.add(rs.getString("suplayer_id")+"-"+rs.getString("name"));
                }
            
                list1.setListData(v);
            }else{
                ResultSet rs=  db.serch("SELECT * FROM suplayer WHERE stat=1 AND name LIKE '"+txtSearch.getText().toUpperCase()+"%'");
                java.util.Vector v = new java.util.Vector();
                 jScrollPane2.setVisible(false);
                while(rs.next()){
                    jScrollPane2.setVisible(true);
                    v.add(rs.getString("supalyer_id")+"-"+rs.getString("name"));  
                }
                list1.setListData(v);
            }
            }else{
             jScrollPane2.setVisible(false);
            }
      
}catch(Exception e){
e.printStackTrace();
}
    

    }

   /* private void list1MouseClicked(java.awt.event.MouseEvent evt) {                                   
     
    }//GEN-LAST:event_txtSearchKeyReleased
*/
    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
              loadText();
    }//GEN-LAST:event_jTable1MousePressed

    private void txtnic1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnic1KeyTyped
                                     
       if(!Character.isDigit(evt.getKeyChar())){
        evt.consume();
               // JOptionPane.showMessageDialog(this, "Sorry your enter string type");
        }
    }//GEN-LAST:event_txtnic1KeyTyped

    private void txtfnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfnKeyTyped
         char keychar =evt.getKeyChar();
        boolean isDigit = Character.isDigit(keychar);
        if(isDigit){
        evt.consume();
        }
    }//GEN-LAST:event_txtfnKeyTyped

    private void txtlnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlnKeyTyped
         char keychar =evt.getKeyChar();
        boolean isDigit = Character.isDigit(keychar);
        if(isDigit){
        evt.consume();
        }
    }//GEN-LAST:event_txtlnKeyTyped

    private void txtcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaKeyTyped
       if(txtca.getText().length()==10){
          evt.consume();
         }
        
        if(!Character.isDigit(evt.getKeyChar())){
        evt.consume();
               // JOptionPane.showMessageDialog(this, "Sorry your enter string type");
        }
    }//GEN-LAST:event_txtcaKeyTyped

    private void txtnic1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnic1KeyPressed
        if(evt.getKeyCode()==8){
       txtnic1.setEditable(true);
       }
    }//GEN-LAST:event_txtnic1KeyPressed

    private void txtnic1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnic1KeyReleased
        if(txtnic1.getText().length()==9){
              txtnic1.setText(txtnic1.getText().concat("V"));
            }else
              if(txtnic1.getText().contains("V")||txtnic1.getText().length()!=10){
             txtnic1.setText(txtnic1.getText().replace("V", ""));
          }
         if(txtnic1.getText().length()==12){
                txtnic1.setEditable(false);
                  }
    }//GEN-LAST:event_txtnic1KeyReleased

    private void txtnic1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnic1MouseClicked
    txtnic1.setEditable(true);

    }//GEN-LAST:event_txtnic1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
          UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateSuplayer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndash;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> list1;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtca;
    private javax.swing.JTextField txtea;
    private javax.swing.JTextField txtfn;
    private javax.swing.JTextField txtln;
    private javax.swing.JTextField txtnic1;
    private javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables

    private void seachem() {
         
        try {
     ResultSet rs = db.serch("select * from suplayer where suplayer_id='"+txtSearch.getText()+"'");
            stop=true;
            //bc.setVisible(true);
            //bu.setVisible(true);
         DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
         dtm.setRowCount(0);
         while(rs.next()){
         
         java.util.Vector v =new java.util.Vector ();
         v.add(rs.getString("suplayer_id"));
         v.add(rs.getString("nic"));
          v.add(rs.getString("name"));
            v.add(rs.getString("company"));
         v.add(rs.getString("phone"));
         v.add(rs.getString("email"));
         v.add(rs.getString("register_date"));
         dtm.addRow(v);
                
         }
        // txtSearch.setText(null);
        } catch (Exception e) {
            e.printStackTrace();
        }
         
    }

    private void loadText2() {
        try {
            ResultSet serch = db.serch("SELECT * FROM suplayer WHERE suplayer_id='"+txtSearch.getText().toUpperCase()+"'");
            if(serch.next()){
           txtfn.setText(serch.getString("name"));
           txtln.setText(serch.getString("company"));
           txtnic1.setText(serch.getString("nic"));
           txtca.setText(serch.getString("phone"));
           txtea.setText(serch.getString("email"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadcustomer() {
         try {
            ResultSet rs = db.serch("select * from suplayer where stat =1");
            DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
           while(rs.next()){
         java.util.Vector v =new java.util.Vector ();
         v.add(rs.getString("suplayer_id"));
         v.add(rs.getString("nic"));
          v.add(rs.getString("name"));
            v.add(rs.getString("company"));
         v.add(rs.getString("phone"));
         v.add(rs.getString("email"));
         v.add(rs.getString("register_date"));
         dtm.addRow(v);
           }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadText() {
          try{
            
              if(stop){
        DefaultTableModel df =(DefaultTableModel)jTable1.getModel();
       java.util.Vector v = new java.util.Vector();
       for(int x = 0;x<jTable1.getColumnCount();x++){
       String s = df.getValueAt(jTable1.getSelectedRow(), x).toString();
       v.add(s);
       }
       
      txtSearch.setText(v.get(0).toString());
      txtnic1.setText(v.get(1).toString());
       txtfn.setText(v.get(2).toString());
      txtca.setText(v.get(3).toString());
      txtea.setText(v.get(4).toString());
      
              }
       }catch(Exception e){}
    }
}
    


