package po;


import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import common.Checknull;
import common.SystemData;
import common.TbView;
import common.db;
import finel_project_gamdora.main_menu;
import finel_project_gamdora.main_menu;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Savepoint;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author udesh
 */
public class item_order extends javax.swing.JFrame {

    /**
     * Creates new form item_order
     */
    public item_order() {
        initComponents();
        screensize();
        TbView.tableSettings(jTable1);
        ponumber();
       
         jScrollPane4.setVisible(false);
          jscole1.setVisible(false);
    }
     boolean stop =false;
     private void screensize() {
      
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        list2 = new javax.swing.JList<>();
        jLabel21 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        txtpo = new javax.swing.JTextField();
        btndash2 = new javax.swing.JButton();
        btndash = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jscole1 = new javax.swing.JScrollPane();
        list3 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtReDate = new com.toedter.calendar.JDateChooser();
        jButton6 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        txtItemId = new javax.swing.JTextField();
        txtSup = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1830, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        list2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list2MouseClicked(evt);
            }
        });
        list2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                list2KeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(list2);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 240, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("PO Number");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 80, 130, 30));

        txtQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtyKeyTyped(evt);
            }
        });
        getContentPane().add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 240, 30));

        txtpo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpoActionPerformed(evt);
            }
        });
        getContentPane().add(txtpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 80, 240, 30));

        btndash2.setBackground(new java.awt.Color(0, 0, 51));
        btndash2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndash2.setForeground(new java.awt.Color(255, 255, 255));
        btndash2.setText(" PO Delete");
        btndash2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btndash2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndash2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndash2MouseExited(evt);
            }
        });
        btndash2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndash2ActionPerformed(evt);
            }
        });
        getContentPane().add(btndash2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 30));

        btndash.setBackground(new java.awt.Color(0, 0, 51));
        btndash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndash.setForeground(new java.awt.Color(255, 255, 255));
        btndash.setText(" DashBoard");
        btndash.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btndash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndashMouseExited(evt);
            }
        });
        btndash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndashActionPerformed(evt);
            }
        });
        getContentPane().add(btndash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 250, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("  Gamdora Distriburtors");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        jLabel3.setBackground(new java.awt.Color(0, 102, 0));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 60));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 1048, -1, -1));

        list3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list3MouseClicked(evt);
            }
        });
        list3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                list3KeyReleased(evt);
            }
        });
        jscole1.setViewportView(list3);

        getContentPane().add(jscole1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 240, 50));

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 1120));

        jLabel4.setBackground(new java.awt.Color(0, 0, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("   Item Order Menu");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 1050, 70));

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("setting");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 70, 30));

        jTable1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Id", "Item Name", "Qunantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 630, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Item Id");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 160, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Suplayer");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 120, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Po Description");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 140, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Receved Date");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 140, 30));
        getContentPane().add(txtReDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 240, 30));

        jButton6.setBackground(new java.awt.Color(0, 0, 102));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText(" Save");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 590, 180, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Quantity");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 120, 30));

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescriptionKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtDescription);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 240, -1));

        txtItemId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtItemId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemIdActionPerformed(evt);
            }
        });
        txtItemId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtItemIdKeyReleased(evt);
            }
        });
        getContentPane().add(txtItemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 240, 30));

        txtSup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupActionPerformed(evt);
            }
        });
        txtSup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupKeyReleased(evt);
            }
        });
        getContentPane().add(txtSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 240, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btndashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashMouseEntered
        btndash.setBackground(Color.BLUE);
    }//GEN-LAST:event_btndashMouseEntered

    private void btndashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashMouseExited
        btndash.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_btndashMouseExited

    private void btndashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashActionPerformed
        new main_menu().setVisible(true);
    }//GEN-LAST:event_btndashActionPerformed

    private void txtpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpoActionPerformed
              Checknull.checkNull(txtpo, "po id", txtSup);     
    }//GEN-LAST:event_txtpoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        addData();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btndash2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndash2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btndash2MouseEntered

    private void btndash2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndash2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btndash2MouseExited

    private void btndash2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndash2ActionPerformed
          new item_orde_delete().setVisible(true);
    }//GEN-LAST:event_btndash2ActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        Checknull.checkNull(txtQty, "qty", txtQty);
        tbData();
    }//GEN-LAST:event_txtQtyActionPerformed

    private void txtItemIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemIdActionPerformed
              Checknull.checkNull(txtItemId, "item", txtQty);       
    }//GEN-LAST:event_txtItemIdActionPerformed

    private void txtItemIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemIdKeyReleased
        try{
            if(!txtItemId.getText().trim().equals("")){
                if(txtItemId.getText().toUpperCase().contains("I")){
                    ResultSet rs=  db.serch("SELECT * FROM item WHERE stat=1 AND item_id  LIKE '"+txtItemId.getText().toUpperCase()+"%'");
                    java.util.Vector v = new java.util.Vector();
                    jScrollPane4.setVisible(false);
                    while(rs.next()){
                        jScrollPane4.setVisible(true);
                        v.add(rs.getString("item_id")+"-"+rs.getString("name"));
                    }
                    list2.setListData(v);
                }else{
                    ResultSet rs=  db.serch("SELECT * FROM item WHERE stat=1 AND name LIKE '"+txtItemId.getText().toUpperCase()+"%'");
                    java.util.Vector v = new java.util.Vector();
                    jScrollPane4.setVisible(false);
                    while(rs.next()){
                        jScrollPane4.setVisible(true);
                        v.add(rs.getString("item_id")+"-"+rs.getString("name"));
                    }
                    list2.setListData(v);
                }
            }else{
                jScrollPane4.setVisible(false);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtItemIdKeyReleased

    private void list2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list2MouseClicked
        if(evt.getClickCount()==2){
            txtItemId.setText(list2.getSelectedValue().split("-")[0]);

            
            
            jScrollPane4.setVisible(false);

        }
    }//GEN-LAST:event_list2MouseClicked

    private void list2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_list2KeyReleased
        //
    }//GEN-LAST:event_list2KeyReleased

    private void txtSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupActionPerformed
             Checknull.checkNull(txtSup, "suplayer", txtSup);
    }//GEN-LAST:event_txtSupActionPerformed

    private void txtSupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupKeyReleased
        try{
            if(!txtSup.getText().trim().equals("")){
                if(txtSup.getText().toUpperCase().contains("S")){
                    ResultSet rs=  db.serch("SELECT * FROM  suplayer WHERE stat=1 AND suplayer_id  LIKE '"+txtSup.getText().toUpperCase()+"%'");
                    java.util.Vector v = new java.util.Vector();
                    jscole1.setVisible(false);
                    while(rs.next()){
                        jscole1.setVisible(true);
                        v.add(rs.getString("suplayer_id")+"-"+rs.getString("name"));
                    }
                    list3.setListData(v);
                }else{
                    ResultSet rs=  db.serch("SELECT * FROM suplayer WHERE stat=1 AND name LIKE '"+txtSup.getText().toUpperCase()+"%'");
                    java.util.Vector v = new java.util.Vector();
                    jscole1.setVisible(false);
                    while(rs.next()){
                        jscole1.setVisible(true);
                        v.add(rs.getString("suplayer_id")+"-"+rs.getString("name"));
                    }
                    list3.setListData(v);
                }
            }else{
                jscole1.setVisible(false);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtSupKeyReleased

    private void list3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list3MouseClicked
        if(evt.getClickCount()==2){
            txtSup.setText(list3.getSelectedValue().split("-")[0]);

            jscole1.setVisible(false);

        }
    }//GEN-LAST:event_list3MouseClicked

    private void list3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_list3KeyReleased

    }//GEN-LAST:event_list3KeyReleased

    private void txtQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyTyped
       if(txtQty.getText().length()==10){
          evt.consume();
         }
    }//GEN-LAST:event_txtQtyKeyTyped

    private void txtDescriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescriptionKeyTyped
        if(txtDescription.getText().length()==100){
          evt.consume();
         }
    }//GEN-LAST:event_txtDescriptionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
          UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new item_order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndash;
    private javax.swing.JButton btndash2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane jscole1;
    private javax.swing.JList<String> list2;
    private javax.swing.JList<String> list3;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtItemId;
    private javax.swing.JTextField txtQty;
    private com.toedter.calendar.JDateChooser txtReDate;
    private javax.swing.JTextField txtSup;
    private javax.swing.JTextField txtpo;
    // End of variables declaration//GEN-END:variables

    private void ponumber() {
         try {
            ResultSet rs = db.serch("select count(po_id) as x from po");
            if(rs.next()){
                String counts = rs.getString("x");
                
                int count = Integer.parseInt(counts);
               ++count;
                if(count<10){
                txtpo.setText("PN000"+count);
               // txtmi.setEditable(false);
                }else if(count<100){
                 txtpo.setText("PN00"+count);
               // txtmi.setEditable(false);
                }else if(count<1000){
                    txtpo.setText("PN0"+count);
                //txtmi.setEditable(false);
                }else if(count<10000){
                    txtpo.setText("PN"+count);
               // txtmi.setEditable(false);
                }
                  txtSup.grabFocus();
            }
           
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void tbData() {
        try {
            if(!txtItemId.getText().equals("")){
            DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
          
            
         Vector v =new Vector ();
         v.add(txtItemId.getText());
           ResultSet serch = db.serch("SELECT * FROM item WHERE item_id='"+txtItemId.getText()+"'");
         if(serch.next()){
         v.add(serch.getString("name"));
         }
         v.add(txtQty.getText());
            dtm.addRow(v);
            
           
            clearTextFeald();
            }else{
             JOptionPane.showMessageDialog(this, "Emty Item ID !!!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clearTextFeald() {
       txtItemId.setText(null);
       txtQty.setText(null);
    }

    private void addData() {
      try {
            db.getNewConnection().setAutoCommit(false);
          Savepoint savepoint= db.getNewConnection().setSavepoint();
            try {
              
              
                  String registerDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
                   Date reDate= txtReDate.getDate();
           SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                db.iud("INSERT INTO po VALUES('"+txtpo.getText()+"','"+txtSup.getText().toUpperCase()+"',"
                        + "'"+sdf.format(reDate)+"','"+txtDescription.getText()+"','"+SystemData.getEmployee()+"','"+registerDate+"','"+1+"')");
                System.out.println("1");
                for(int row =0; row < jTable1.getRowCount();row++){
            String itemid=jTable1.getValueAt(row, 0).toString().trim();
            String qty=jTable1.getValueAt(row, 2).toString().trim();
                    System.out.println("2");
                 
              
            db.iud("INSERT INTO po_item (po_id,item_id,qty,stat) VALUES('"+txtpo.getText()+"','"+itemid+"','"+qty+"','"+1+"')");
                    
                   
           }
                 JOptionPane.showMessageDialog(this, "successful !!!");
                  saveclear();
            } catch (Exception e) {
                db.getNewConnection().rollback(savepoint);
            e.printStackTrace();
            }
            db.getNewConnection().commit();
        db.getNewConnection().setAutoCommit(true);
       
        } catch (Exception e) {
        }
    }

    private void saveclear() {
      txtDescription.setText(null);
      txtItemId.setText(null);
      txtQty.setText(null);
      txtSup.setText(null);
      txtpo.setText(null);
      txtReDate.setDate(null);
      DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
    }
}