/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package po;

import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import common.Checknull;
import common.TbView;
import common.db;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author udesh
 */
public class item_orde_delete extends javax.swing.JFrame {

    /**
     * Creates new form item_orde_delete
     */
    public item_orde_delete() {
        initComponents();
         screensize();
           TbView.tableSettings(jTable1);
           jScrollPane4.setVisible(false);
    }
    boolean stop =false;
 private void screensize() {
      
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btndash = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtpoid = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        list2 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        txtsup = new javax.swing.JTextField();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        pode = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1840, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 87, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 153));
        jLabel6.setText(" Seach By PO ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, 210, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("  Gamdora Distriburtors");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        jLabel3.setBackground(new java.awt.Color(0, 102, 0));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 60));

        btndash.setBackground(new java.awt.Color(0, 0, 51));
        btndash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndash.setForeground(new java.awt.Color(255, 255, 255));
        btndash.setText("Back");
        btndash.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btndash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndashMouseExited(evt);
            }
        });
        btndash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndashActionPerformed(evt);
            }
        });
        getContentPane().add(btndash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 1120));

        txtpoid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtpoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpoidActionPerformed(evt);
            }
        });
        txtpoid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpoidKeyReleased(evt);
            }
        });
        getContentPane().add(txtpoid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 80, 240, 30));

        list2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list2MouseClicked(evt);
            }
        });
        list2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                list2KeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(list2);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 110, 240, 60));

        jLabel4.setBackground(new java.awt.Color(0, 0, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("   PO Delete");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 1050, 70));

        txtsup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsupActionPerformed(evt);
            }
        });
        getContentPane().add(txtsup, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 240, 30));
        getContentPane().add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 240, 30));

        pode.setColumns(20);
        pode.setRows(5);
        pode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                podeKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(pode);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 240, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Po Description");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 140, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Receved Date");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 140, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Suplayer");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 120, 30));

        jButton6.setBackground(new java.awt.Color(0, 0, 102));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("  Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 590, 180, 30));

        jTable1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Id", "Item Name", "Qunantity"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 630, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("setting");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 70, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashMouseEntered
        btndash.setBackground(Color.BLUE);
    }//GEN-LAST:event_btndashMouseEntered

    private void btndashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashMouseExited
        btndash.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_btndashMouseExited

    private void btndashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashActionPerformed
        new item_order().setVisible(true);
    }//GEN-LAST:event_btndashActionPerformed

    private void txtsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsupActionPerformed
       Checknull.checkNull(txtsup, "suplayer", txtsup);
    }//GEN-LAST:event_txtsupActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
          try {
         
        db.iud("update po set stat='"+"0"+"' where po_id='"+txtpoid.getText()+"'");
          JOptionPane.showMessageDialog(this, " "+ txtpoid.getText()+" PO is remove");
     

        } catch (Exception e) {
            e.printStackTrace();
        }
          try {
            db.iud("update po_item set stat='"+"0"+"' where po_id='"+txtpoid.getText()+"'");
          JOptionPane.showMessageDialog(this, " "+ txtpoid.getText()+" PO item is Remove");
        pode.setText(null);
      txtpoid.setText(null);
      txtsup.setText(null);
      jDateChooser3.setDate(null);
      DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);


        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtpoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpoidActionPerformed
      Checknull.checkNull(txtpoid, "poid", txtsup);
    }//GEN-LAST:event_txtpoidActionPerformed

    private void txtpoidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpoidKeyReleased
        try{
            if(!txtpoid.getText().trim().equals("")){
                if(txtpoid.getText().toUpperCase().contains("P")){
                    ResultSet rs=  db.serch("SELECT * FROM po WHERE stat=1 AND po_id  LIKE '"+txtpoid.getText().toUpperCase()+"%'");
                    java.util.Vector v = new java.util.Vector();
                    jScrollPane4.setVisible(false);
                    while(rs.next()){
                        jScrollPane4.setVisible(true);
                        v.add(rs.getString("po_id"));
                    }
                    list2.setListData(v);
                }
            }else{
                jScrollPane4.setVisible(false);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtpoidKeyReleased

    private void list2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list2MouseClicked
        if(evt.getClickCount()==2){
            txtpoid.setText(list2.getSelectedValue().split("-")[0]);
            seachem();
             loadText2();
            jScrollPane4.setVisible(false);

        }
    }//GEN-LAST:event_list2MouseClicked

    private void list2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_list2KeyReleased
        //
    }//GEN-LAST:event_list2KeyReleased

    private void podeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_podeKeyTyped
     if(pode.getText().length()==10){
          evt.consume();
         }
    }//GEN-LAST:event_podeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try {
          UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new item_orde_delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndash;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> list2;
    private javax.swing.JTextArea pode;
    private javax.swing.JTextField txtpoid;
    private javax.swing.JTextField txtsup;
    // End of variables declaration//GEN-END:variables

    private void seachem() {
          try {
     ResultSet rs = db.serch("select * from po_item where po_id='"+txtpoid.getText()+"'");
         DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
         dtm.setRowCount(0);
         while(rs.next()){
          Vector v =new Vector ();
         v.add(rs.getString("item_id"));
           ResultSet serch = db.serch("SELECT * FROM item WHERE item_id='"+rs.getString("item_id")+"'");
         if(serch.next()){
         v.add(serch.getString("name"));
         }
         v.add(rs.getString("qty"));
          
         
            dtm.addRow(v);
            
         }
        // txtSearch.setText(null);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadText2() {
        try {
            ResultSet serch = db.serch("SELECT * FROM po WHERE po_id='"+txtpoid.getText().toUpperCase()+"'");
            if(serch.next()){
           txtsup.setText(serch.getString("suplayer"));
           jDateChooser3.setDate(serch.getDate("receve_date"));
           pode.setText(serch.getString("description"));
          
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
