/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grn;

import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import common.Checknull;
import common.TbView;
import common.db;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Savepoint;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author udesh
 */
public class add_item extends javax.swing.JFrame {

    /**
     * Creates new form add_item
     */
    public add_item() {
        initComponents();
        screensize();
          TbView.tableSettings(jTable1);
          jScrollPane7.setVisible(false);
           jscole1.setVisible(false);
           textfeld();
          
           
           GRNNO();
    }
     boolean stop =false;
     private void screensize() {
      
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jscole1 = new javax.swing.JScrollPane();
        list3 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        list5 = new javax.swing.JList<>();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel16 = new javax.swing.JLabel();
        btndash = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtItemId = new javax.swing.JTextField();
        txtgrn = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtBuyPrice = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtTotDis = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtNetAm = new javax.swing.JTextField();
        txtSellPrice = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtSup = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1840, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        list3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list3MouseClicked(evt);
            }
        });
        list3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                list3KeyReleased(evt);
            }
        });
        jscole1.setViewportView(list3);

        getContentPane().add(jscole1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 240, 0));

        list5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list5MouseClicked(evt);
            }
        });
        list5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                list5KeyReleased(evt);
            }
        });
        jScrollPane7.setViewportView(list5);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 240, 30));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 977, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("  Gamdora Distriburtors");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        btndash.setBackground(new java.awt.Color(0, 0, 51));
        btndash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndash.setForeground(new java.awt.Color(255, 255, 255));
        btndash.setText("Back");
        btndash.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btndash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndashMouseExited(evt);
            }
        });
        btndash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndashActionPerformed(evt);
            }
        });
        getContentPane().add(btndash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 30));

        jLabel3.setBackground(new java.awt.Color(0, 102, 0));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 60));

        txtItemId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtItemId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemIdActionPerformed(evt);
            }
        });
        txtItemId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtItemIdKeyReleased(evt);
            }
        });
        getContentPane().add(txtItemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 240, 50));

        txtgrn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtgrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgrnActionPerformed(evt);
            }
        });
        getContentPane().add(txtgrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 81, 240, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("GRN ID");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 81, 130, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 1100));

        jLabel4.setBackground(new java.awt.Color(0, 0, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("     Good Recive Note");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 61, 1050, 70));

        jTable1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Id", "Item Name", "Quantity", "Buying Price", "Selling Price", "Discount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(678, 161, 660, 330));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 161, 120, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Item Id");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 119, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Suplayer");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 120, 30));

        txtDiscount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountActionPerformed(evt);
            }
        });
        txtDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDiscountKeyTyped(evt);
            }
        });
        getContentPane().add(txtDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 240, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Quantity");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 120, 30));

        txtQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtyKeyTyped(evt);
            }
        });
        getContentPane().add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 240, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("setting");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 11, 70, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Buying Price");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 120, 30));

        txtBuyPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtBuyPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuyPriceActionPerformed(evt);
            }
        });
        txtBuyPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuyPriceKeyTyped(evt);
            }
        });
        getContentPane().add(txtBuyPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 240, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Discount");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 120, 30));

        txtTotDis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTotDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotDisActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotDis, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 520, 240, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Total Discount");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 140, 30));

        jButton6.setBackground(new java.awt.Color(0, 0, 102));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText(" Save");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 661, 180, 50));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Amount");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 80, 30));

        txtAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        getContentPane().add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 240, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Net Amount");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 570, 120, 30));

        txtNetAm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNetAm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNetAmActionPerformed(evt);
            }
        });
        getContentPane().add(txtNetAm, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 570, 240, 30));

        txtSellPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSellPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSellPriceActionPerformed(evt);
            }
        });
        txtSellPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSellPriceKeyTyped(evt);
            }
        });
        getContentPane().add(txtSellPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 240, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Selling Price");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 120, 30));

        txtSup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupActionPerformed(evt);
            }
        });
        txtSup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupKeyReleased(evt);
            }
        });
        getContentPane().add(txtSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 240, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountActionPerformed
        Checknull.checkNull(txtDiscount, "discount", txtDiscount);

        tbData();
    }//GEN-LAST:event_txtDiscountActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        Checknull.checkNull(txtQty, "qty", txtBuyPrice);
    }//GEN-LAST:event_txtQtyActionPerformed

    private void txtBuyPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuyPriceActionPerformed
        Checknull.checkNull(txtBuyPrice, "BuyPrice", txtSellPrice);
    }//GEN-LAST:event_txtBuyPriceActionPerformed

    private void txtTotDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotDisActionPerformed
           

    }//GEN-LAST:event_txtTotDisActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            db.getNewConnection().setAutoCommit(false);
          Savepoint savepoint= db.getNewConnection().setSavepoint();
            try {
              
              
                  String registerDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
                db.iud("INSERT INTO grn VALUES('"+txtgrn.getText()+"','"+txtSup.getText().toUpperCase()+"',"
                        + "'"+txtAmount.getText()+"','"+txtTotDis.getText()+"','"+common.SystemData.getEmployee()+"','"+registerDate+"','"+1+"')");
                
                for(int row =0; row < jTable1.getRowCount();row++){
            String itemid=jTable1.getValueAt(row, 0).toString().trim();
            String qty=jTable1.getValueAt(row, 2).toString().trim();
            int qty1=Integer.parseInt(qty);
            String buingPrice=jTable1.getValueAt(row, 3).toString().trim();
            String sellingPrice=jTable1.getValueAt(row, 4).toString().trim();
            String discount=jTable1.getValueAt(row, 5).toString().trim();
                    System.out.println("1");
            String grnItemSQL="INSERT INTO grn_item (item_id,grn_id,qty,buing_price,selling_price,discount,stat) VALUES('"+itemid+"','"+txtgrn.getText()+"','"+qty+"','"+buingPrice+"','"+sellingPrice+"','"+discount+"','"+1+"')";
            db.iud(grnItemSQL);
                    System.out.println("2");
             ResultSet serch = db.serch("SELECT * FROM stock WHERE item_id='"+itemid+"'");
                    System.out.println("3");
            if(serch.next()){
                System.out.println("4");
                System.out.println(buingPrice);
                System.out.println(serch.getString("buing_price"));
                if(serch.getString("buing_price").equals(buingPrice)){
                    System.out.println("8");
                if(serch.getString("qty").equals("0")){
                    System.out.println("9");
                     int qtyD=serch.getInt("qty");
                
                 int qt2 =qty1+qtyD;
                db.iud("UPDATE stock set qty='"+qt2+"' where item_id='"+itemid+"' AND selling_price='"+sellingPrice+"'");
               
                }else{
                if(serch.getString("selling_price").equals(sellingPrice)){
                    System.out.println("10");
                      int qtyD=serch.getInt("qty");
                
                 int qt2 =qty1+qtyD;
                 
                    db.iud("UPDATE stock set qty='"+qt2+"' where item_id='"+itemid+"' AND selling_price='"+sellingPrice+"'");
                  System.out.println("11");
                }else{
                 db.iud("INSERT INTO stock (item_id,qty,buing_price,selling_price,stat) VALUES ('"+itemid+"','"+qty+"','"+buingPrice+"','"+sellingPrice+"','"+1+"')");
                }
                }
                }else{
                 db.iud("INSERT INTO stock (item_id,qty,buing_price,selling_price,stat) VALUES ('"+itemid+"','"+qty+"','"+buingPrice+"','"+sellingPrice+"','"+1+"')");
                }
            }else{
                System.out.println("5");
            db.iud("INSERT INTO stock (item_id,qty,buing_price,selling_price,stat) VALUES('"+itemid+"','"+qty+"','"+buingPrice+"','"+sellingPrice+"','"+1+"')");
                System.out.println("6");
            }
                    JOptionPane.showMessageDialog(this, "successful !!!");
           }
 
            } catch (Exception e) {
                db.getNewConnection().rollback(savepoint);
            e.printStackTrace();
            }
            db.getNewConnection().commit();
        db.getNewConnection().setAutoCommit(true);
        saveclear();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void txtNetAmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNetAmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNetAmActionPerformed

    private void txtSellPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSellPriceActionPerformed
                Checknull.checkNull(txtSellPrice, "sell ", txtDiscount);

    }//GEN-LAST:event_txtSellPriceActionPerformed

    private void btndashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashActionPerformed
        new GRN_viwe().setVisible(true);
    }//GEN-LAST:event_btndashActionPerformed

    private void btndashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashMouseExited
        btndash.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_btndashMouseExited

    private void btndashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashMouseEntered
        btndash.setBackground(Color.BLUE);
    }//GEN-LAST:event_btndashMouseEntered

    private void txtgrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgrnActionPerformed
      
    }//GEN-LAST:event_txtgrnActionPerformed

    private void txtItemIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemIdActionPerformed
                Checknull.checkNull(txtItemId, "ITEM", txtQty);        
    }//GEN-LAST:event_txtItemIdActionPerformed

    private void txtItemIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemIdKeyReleased
        try{
            if(!txtItemId.getText().trim().equals("")){
                if(txtItemId.getText().toUpperCase().contains("I")){
                    ResultSet rs=  db.serch("SELECT * FROM item WHERE stat=1 AND item_id  LIKE '"+txtItemId.getText().toUpperCase()+"%'");
                    java.util.Vector v = new java.util.Vector();
                    jScrollPane7.setVisible(false);
                    while(rs.next()){
                        jScrollPane7.setVisible(true);
                        v.add(rs.getString("item_id")+"-"+rs.getString("name"));
                    }
                    list5.setListData(v);
                }else{
                    ResultSet rs=  db.serch("SELECT * FROM item WHERE stat=1 AND name LIKE '"+txtItemId.getText().toUpperCase()+"%'");
                    java.util.Vector v = new java.util.Vector();
                    jScrollPane7.setVisible(false);
                    while(rs.next()){
                        jScrollPane7.setVisible(true);
                        v.add(rs.getString("item_id")+"-"+rs.getString("name"));
                    }
                    list5.setListData(v);
                }
            }else{
                jScrollPane7.setVisible(false);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtItemIdKeyReleased

    private void list5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list5MouseClicked
        if(evt.getClickCount()==2){
            txtItemId.setText(list5.getSelectedValue().split("-")[0]);
            
           
            jScrollPane7.setVisible(false);

        }
    }//GEN-LAST:event_list5MouseClicked

    private void list5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_list5KeyReleased

    }//GEN-LAST:event_list5KeyReleased

    private void txtSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupActionPerformed
              Checknull.checkNull(txtSup, "suplayer", txtItemId);
    }//GEN-LAST:event_txtSupActionPerformed

    private void txtSupKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupKeyReleased
        try{
            if(!txtSup.getText().trim().equals("")){
                if(txtSup.getText().toUpperCase().contains("S")){
                    ResultSet rs=  db.serch("SELECT * FROM  suplayer WHERE stat=1 AND suplayer_id  LIKE '"+txtSup.getText().toUpperCase()+"%'");
                    java.util.Vector v = new java.util.Vector();
                    jscole1.setVisible(false);
                    while(rs.next()){
                        jscole1.setVisible(true);
                        v.add(rs.getString("suplayer_id")+"-"+rs.getString("name"));
                    }
                    list3.setListData(v);
                }else{
                    ResultSet rs=  db.serch("SELECT * FROM suplayer WHERE stat=1 AND name LIKE '"+txtSup.getText().toUpperCase()+"%'");
                    java.util.Vector v = new java.util.Vector();
                    jscole1.setVisible(false);
                    while(rs.next()){
                        jscole1.setVisible(true);
                        v.add(rs.getString("suplayer_id")+"-"+rs.getString("name"));
                    }
                    list3.setListData(v);
                }
            }else{
                jscole1.setVisible(false);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtSupKeyReleased

    private void list3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list3MouseClicked
        if(evt.getClickCount()==2){
            txtSup.setText(list3.getSelectedValue().split("-")[0]);

            jscole1.setVisible(false);

        }
    }//GEN-LAST:event_list3MouseClicked

    private void list3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_list3KeyReleased

    }//GEN-LAST:event_list3KeyReleased

    private void txtQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyTyped
         if(txtQty.getText().length()==1000){
          evt.consume();
         }
    }//GEN-LAST:event_txtQtyKeyTyped

    private void txtBuyPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuyPriceKeyTyped
         if(txtBuyPrice.getText().length()==100000){
          evt.consume();
         }
    }//GEN-LAST:event_txtBuyPriceKeyTyped

    private void txtSellPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSellPriceKeyTyped
        if(txtSellPrice.getText().length()==100000){
          evt.consume();
         }
    }//GEN-LAST:event_txtSellPriceKeyTyped

    private void txtDiscountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscountKeyTyped
         if(txtDiscount.getText().length()==1000){
          evt.consume();
         }
    }//GEN-LAST:event_txtDiscountKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try {
          UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_item().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndash;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane jscole1;
    private javax.swing.JList<String> list3;
    private javax.swing.JList<String> list5;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBuyPrice;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtItemId;
    private javax.swing.JTextField txtNetAm;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSellPrice;
    private javax.swing.JTextField txtSup;
    private javax.swing.JTextField txtTotDis;
    private javax.swing.JTextField txtgrn;
    // End of variables declaration//GEN-END:variables

    private void GRNNO() {
          try {
            ResultSet rs = db.serch("select count(grn_id) as x from grn");
            if(rs.next()){
                String counts = rs.getString("x");
                
                int count = Integer.parseInt(counts);
               ++count;
                if(count<10){
                txtgrn.setText("GR000"+count);
               // txtmi.setEditable(false);
                }else if(count<100){
                 txtgrn.setText("GR00"+count);
               // txtmi.setEditable(false);
                }else if(count<1000){
                    txtgrn.setText("GR0"+count);
                //txtmi.setEditable(false);
                }else if(count<10000){
                    txtgrn.setText("GR"+count);
               // txtmi.setEditable(false);
                }
                 
            }
           
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void tbData() {
       try {
            DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
          
            
         Vector v =new Vector ();
         v.add(txtItemId.getText());
           ResultSet serch = db.serch("SELECT * FROM item WHERE item_id='"+txtItemId.getText()+"'");
         if(serch.next()){
         v.add(serch.getString("name"));
         }
         v.add(txtQty.getText());
         DecimalFormat df = new DecimalFormat("0.00");
           String buingPrice =df.format(Double.parseDouble(txtBuyPrice.getText()));
           String sellingPrice =df.format(Double.parseDouble(txtSellPrice.getText()));
           String discount1 =df.format(Double.parseDouble(txtDiscount.getText()));
         v.add(buingPrice);
           System.out.println(buingPrice);
         v.add(sellingPrice);
         v.add(discount1);
            dtm.addRow(v);
            
            double amount= Double.parseDouble(txtAmount.getText());
            amount=amount+(Double.parseDouble(txtBuyPrice.getText()))*Integer.parseInt(txtQty.getText());
            txtAmount.setText(String.valueOf(amount));
            
            double discount= Double.parseDouble(txtTotDis.getText());
            discount=discount+(Double.parseDouble(txtDiscount.getText()))*Integer.parseInt(txtQty.getText());
            txtTotDis.setText(String.valueOf(discount));
            txtNetAm.setText(String.valueOf(amount-discount));
            clearTextFeald();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void textfeld() {
        txtAmount.setText("0");
           txtTotDis.setText("0");
           txtNetAm.setText("0");
       txtAmount.setEditable(false);
       txtTotDis.setEditable(false);
      txtNetAm.setEditable(false);
      txtSup.grabFocus();
    }

    private void clearTextFeald() {
       txtItemId.setText(null);
       txtQty.setText(null);
       txtBuyPrice.setText(null);
       txtSellPrice.setText(null);
       txtDiscount.setText(null);
       txtItemId.grabFocus();
    }

    private void saveclear() {
        txtAmount.setText(null);
         txtItemId.setText(null);
       txtQty.setText(null);
       txtBuyPrice.setText(null);
       txtSellPrice.setText(null);
       txtDiscount.setText(null);
       txtSup.setText(null);
       txtTotDis.setText(null);
       txtNetAm.setText(null);
       txtgrn.setText(null);
      
        DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
       GRNNO();
    }

}