/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package customer;

import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import common.TbView;
import common.db;
import finel_project_gamdora.main_menu;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author udesh
 */
public class customer_menegment extends javax.swing.JFrame {

    /**
     * Creates new form customer_menegment
     */
    public customer_menegment() {
        initComponents();
        screensize();
          TbView.tableSettings(jTable1);
          Loadcustomer();
    }
private void screensize() {
      
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    
}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnupc1 = new javax.swing.JButton();
        btnupc = new javax.swing.JButton();
        btncr = new javax.swing.JButton();
        btndash = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1840, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 68, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("  Gamdora Distriburtors");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        jLabel3.setBackground(new java.awt.Color(0, 102, 0));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 60));

        btnupc1.setBackground(new java.awt.Color(0, 0, 51));
        btnupc1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnupc1.setForeground(new java.awt.Color(255, 255, 255));
        btnupc1.setText(" Remove Customer");
        btnupc1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnupc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnupc1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnupc1MouseExited(evt);
            }
        });
        btnupc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupc1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnupc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 30));

        btnupc.setBackground(new java.awt.Color(0, 0, 51));
        btnupc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnupc.setForeground(new java.awt.Color(255, 255, 255));
        btnupc.setText(" Update Customer");
        btnupc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnupc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnupcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnupcMouseExited(evt);
            }
        });
        btnupc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupcActionPerformed(evt);
            }
        });
        getContentPane().add(btnupc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 250, 30));

        btncr.setBackground(new java.awt.Color(0, 0, 51));
        btncr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncr.setForeground(new java.awt.Color(255, 255, 255));
        btncr.setText("Customer Register");
        btncr.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btncr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncrMouseExited(evt);
            }
        });
        btncr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrActionPerformed(evt);
            }
        });
        getContentPane().add(btncr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 30));

        btndash.setBackground(new java.awt.Color(0, 0, 51));
        btndash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndash.setForeground(new java.awt.Color(255, 255, 255));
        btndash.setText(" DashBoard");
        btndash.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btndash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndashMouseExited(evt);
            }
        });
        btndash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndashActionPerformed(evt);
            }
        });
        getContentPane().add(btndash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 250, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 1220));

        jLabel4.setBackground(new java.awt.Color(0, 0, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Customer  Menegment");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 1050, 70));

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("setting");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 70, 30));

        jTable1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "NIC", "Name", "Address", "Contact No", "Email", "Register Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 1060, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashMouseEntered
        btndash.setBackground(Color.BLUE);
    }//GEN-LAST:event_btndashMouseEntered

    private void btndashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashMouseExited
        btndash.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_btndashMouseExited

    private void btndashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashActionPerformed
        new main_menu().setVisible(true);
    }//GEN-LAST:event_btndashActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btncrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncrMouseEntered
         btncr.setBackground(Color.BLUE);
    }//GEN-LAST:event_btncrMouseEntered

    private void btncrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncrMouseExited
         btncr.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_btncrMouseExited

    private void btncrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrActionPerformed
       new cutomer_register().setVisible(true);
    }//GEN-LAST:event_btncrActionPerformed

    private void btnupcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupcMouseEntered
        btnupc.setBackground(Color.BLUE);
    }//GEN-LAST:event_btnupcMouseEntered

    private void btnupcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupcMouseExited
        btnupc.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_btnupcMouseExited

    private void btnupcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupcActionPerformed
       new Update_customer().setVisible(true);
    }//GEN-LAST:event_btnupcActionPerformed

    private void btnupc1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupc1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnupc1MouseEntered

    private void btnupc1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupc1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnupc1MouseExited

    private void btnupc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupc1ActionPerformed
          new cu_delet().setVisible(true);
    }//GEN-LAST:event_btnupc1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
          UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer_menegment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncr;
    private javax.swing.JButton btndash;
    private javax.swing.JButton btnupc;
    private javax.swing.JButton btnupc1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void Loadcustomer() {
        
         try {
            ResultSet rs = db.serch("select * from customer_register where stat =1");
            DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
             while(rs.next()){
         String name =rs.getString("frist_name")+" "+rs.getString("last_name");
         String adress =rs.getString("ad_l1")+","+rs.getString("ad_l2")+","+rs.getString("ad_l3");
         java.util.Vector v =new java.util.Vector ();
         v.add(rs.getString("customer_id"));
         v.add(rs.getString("nic"));
         v.add(name);
         v.add(adress);
         v.add(rs.getString("contact"));
         v.add(rs.getString("email"));
         v.add(rs.getString("register_date"));
         dtm.addRow(v);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}

    



    

