/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee;

import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import common.Checknull;
import common.TbView;
import common.db;

import java.awt.Color;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author udesh
 */
public class EM_up extends javax.swing.JFrame {

    /**
     * Creates new form EM_up
     */
    public EM_up() {
        initComponents();
        screensize();
        TbView.tableSettings(jTable1);
        Loadmember();
        
        jScrollPane2.setVisible(false);
    }
     boolean stop =false;
private void screensize() {
      
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        btndash = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList<>();
        txtSearch = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        caledob = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtad1 = new javax.swing.JTextField();
        txtad2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtad3 = new javax.swing.JTextField();
        txtcno = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtlname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1840, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("  Gamdora Distriburtors");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        btndash.setBackground(new java.awt.Color(0, 0, 51));
        btndash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndash.setForeground(new java.awt.Color(255, 255, 255));
        btndash.setText("Back");
        btndash.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btndash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndashMouseExited(evt);
            }
        });
        btndash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndashActionPerformed(evt);
            }
        });
        getContentPane().add(btndash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 250, 50));

        list1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list1MouseClicked(evt);
            }
        });
        list1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                list1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(list1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 110, 240, 90));

        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 80, 240, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText(" Search ");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 100, 30));

        jLabel3.setBackground(new java.awt.Color(0, 102, 0));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 60));

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 1220));

        jLabel4.setBackground(new java.awt.Color(0, 0, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("  Employee Update");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 1050, 70));

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("setting");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 70, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("NIC");
        jLabel23.setToolTipText("");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 150, 30));

        txtnic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicActionPerformed(evt);
            }
        });
        txtnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnicKeyTyped(evt);
            }
        });
        getContentPane().add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 240, 30));

        txtfname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        txtfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfnameKeyTyped(evt);
            }
        });
        getContentPane().add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 240, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("First Name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 130, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Last Name");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 130, 30));

        caledob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(caledob, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 240, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("DOB");
        jLabel21.setToolTipText("");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 150, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("L1.");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 50, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("Address");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 120, 30));

        txtad1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtad1ActionPerformed(evt);
            }
        });
        txtad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtad1KeyTyped(evt);
            }
        });
        getContentPane().add(txtad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 240, 30));

        txtad2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtad2ActionPerformed(evt);
            }
        });
        txtad2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtad2KeyTyped(evt);
            }
        });
        getContentPane().add(txtad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 240, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("L2.");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 50, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("L3.");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 50, 30));

        txtad3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtad3ActionPerformed(evt);
            }
        });
        txtad3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtad3KeyTyped(evt);
            }
        });
        getContentPane().add(txtad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 240, 30));

        txtcno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtcno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnoActionPerformed(evt);
            }
        });
        txtcno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcnoKeyTyped(evt);
            }
        });
        getContentPane().add(txtcno, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 240, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Contact NO");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 150, 30));

        jButton8.setBackground(new java.awt.Color(0, 0, 102));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 520, 180, 50));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 611, -1, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "NIC", "Name", "DOB", "Address", "Contact", "Joined Date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 670, 360));

        txtlname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });
        txtlname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlnameKeyTyped(evt);
            }
        });
        getContentPane().add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 240, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicActionPerformed
         Checknull.checkNull(txtnic, "nic", txtfname);
    }//GEN-LAST:event_txtnicActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
         Checknull.checkNull(txtfname, "fname", txtlname);
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtad1ActionPerformed
         Checknull.checkNull(txtad1, "add1", txtad2);
    }//GEN-LAST:event_txtad1ActionPerformed

    private void txtad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtad2ActionPerformed
         Checknull.checkNull(txtad2, "add2", txtad3);
    }//GEN-LAST:event_txtad2ActionPerformed

    private void txtad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtad3ActionPerformed
         Checknull.checkNull(txtad3, "add3", txtcno);
    }//GEN-LAST:event_txtad3ActionPerformed

    private void txtcnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnoActionPerformed
      Checknull.checkNull(txtcno, "contact", txtcno);
      jButton8.grabFocus();
    }//GEN-LAST:event_txtcnoActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
             stop=false;
                
              String employeeId = txtSearch.getText().toUpperCase();
             String nic= txtnic.getText().toUpperCase();
            String firstName= txtfname.getText().toUpperCase();
            String lastName= txtlname.getText().toUpperCase();
           Date dob= caledob.getDate();
           SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
           String adL1= txtad1.getText().toUpperCase();
           String adL2= txtad2.getText().toUpperCase();
           String adL3= txtad3.getText().toUpperCase();
            String contact =txtcno.getText().toUpperCase();
           String registerDate = new SimpleDateFormat("yyyy-MM-dd ").format(new Date());
            db.iud("UPDATE employee SET employee_id='"+employeeId+"',nic='"+nic+"',first_name='"+firstName+"',last_name='"+lastName+"',dob='"+sdf.format(dob)+"',contact='"+contact+"',ad_l1='"+adL1+"',ad_l2='"+adL2+"',ad_l3='"+adL3+"',register_date='"+registerDate+"' where employee_id='"+txtSearch.getText()+"'");
            JOptionPane.showMessageDialog(this, ""+txtSearch.getText()+" IS Successfully update!!");
            
            
             try {
            ResultSet rs = db.serch("SELECT * FROM employee");
         DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
         dtm.setRowCount(0);
         while(rs.next()){
            String name =rs.getString("first_name")+" "+rs.getString("last_name");
              String adress =rs.getString("ad_l1")+","+rs.getString("ad_l2")+","+rs.getString("ad_l3")+"."+("");
         Vector v =new Vector ();
         v.add(rs.getString("employee_id"));
         v.add(rs.getString("nic"));
          v.add(name);
            v.add(rs.getString("dob"));
              v.add(adress);
            v.add(rs.getString("contact"));
             v.add(rs.getString("register_date"));
            dtm.addRow(v);
         }
        } catch (Exception e) {
            e.printStackTrace();
        }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
       
            txtSearch.setText(null);
           txtnic.setText(null);
           txtfname.setText(null);
           txtlname.setText(null);
           caledob.setDate(null);
           txtad1.setText(null);
           txtad2.setText(null);
           txtad3.setText(null);
           txtcno.setText(null);
             
             
             
           
          
         
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btndashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashMouseEntered
        btndash.setBackground(Color.BLUE);
    }//GEN-LAST:event_btndashMouseEntered

    private void btndashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashMouseExited
        btndash.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_btndashMouseExited

    private void btndashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashActionPerformed
       new Emplooye_register().setVisible(true);
    }//GEN-LAST:event_btndashActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
         Checknull.checkNull(txtSearch, "seach", txtnic);
        seachem();
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
         Checknull.checkNull(txtlname, "lname", txtlname);
    }//GEN-LAST:event_txtlnameActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        loadText();
        
        
    }//GEN-LAST:event_jTable1MousePressed

    private void list1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_list1KeyReleased
       
    }//GEN-LAST:event_list1KeyReleased

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
try{
            if(!txtSearch.getText().trim().equals("")){
            if(txtSearch.getText().toUpperCase().contains("E")){
                ResultSet rs=  db.serch("SELECT * FROM employee WHERE stat=1 AND employee_id  LIKE '"+txtSearch.getText().toUpperCase()+"%'");
                Vector v = new Vector();
                       jScrollPane2.setVisible(false);
                while(rs.next()){
                     jScrollPane2.setVisible(true);
                    v.add(rs.getString("employee_id")+"-"+rs.getString("first_name")+" "+rs.getString("last_name"));
                }
                list1.setListData(v);
            }else{
                ResultSet rs=  db.serch("SELECT * FROM employee WHERE stat=1 AND first_name LIKE '"+txtSearch.getText().toUpperCase()+"%'");
                Vector v = new Vector();
                 jScrollPane2.setVisible(false);
                while(rs.next()){
                    jScrollPane2.setVisible(true);
                    v.add(rs.getString("employee_id")+"-"+rs.getString("first_name")+" "+rs.getString("last_name"));  
                }
                list1.setListData(v);
            }
            }else{
             jScrollPane2.setVisible(false);
            }
}catch(Exception e){
e.printStackTrace();
}
    }//GEN-LAST:event_txtSearchKeyReleased

    private void list1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list1MouseClicked
      if(evt.getClickCount()==2){
            txtSearch.setText(list1.getSelectedValue().split("-")[0]);
             seachem();
             loadText2();
            jScrollPane2.setVisible(false);

        }
    }//GEN-LAST:event_list1MouseClicked

    private void txtnicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnicKeyTyped
        if(txtnic.getText().length()==12){
          evt.consume();
       }
    }//GEN-LAST:event_txtnicKeyTyped

    private void txtfnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfnameKeyTyped
      char keychar =evt.getKeyChar();
        boolean isDigit = Character.isDigit(keychar);
        if(isDigit){
        evt.consume();
        }
    }//GEN-LAST:event_txtfnameKeyTyped

    private void txtlnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlnameKeyTyped
    char keychar =evt.getKeyChar();
        boolean isDigit = Character.isDigit(keychar);
        if(isDigit){
        evt.consume();
        }
    }//GEN-LAST:event_txtlnameKeyTyped

    private void txtad1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtad1KeyTyped
        if(txtad1.getText().length()==5){
          evt.consume();
         }
    }//GEN-LAST:event_txtad1KeyTyped

    private void txtad2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtad2KeyTyped
        char keychar =evt.getKeyChar();
        boolean isDigit = Character.isDigit(keychar);
        if(isDigit){
        evt.consume();
        }
    }//GEN-LAST:event_txtad2KeyTyped

    private void txtad3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtad3KeyTyped
       char keychar =evt.getKeyChar();
        boolean isDigit = Character.isDigit(keychar);
        if(isDigit){
        evt.consume();
        }
    }//GEN-LAST:event_txtad3KeyTyped

    private void txtcnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnoKeyTyped
         if(txtcno.getText().length()==10){
          evt.consume();
         }
        
        if(!Character.isDigit(evt.getKeyChar())){
        evt.consume();
               // JOptionPane.showMessageDialog(this, "Sorry your enter string type");
        }
    }//GEN-LAST:event_txtcnoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
          UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EM_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndash;
    private com.toedter.calendar.JDateChooser caledob;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> list1;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtad1;
    private javax.swing.JTextField txtad2;
    private javax.swing.JTextField txtad3;
    private javax.swing.JTextField txtcno;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtnic;
    // End of variables declaration//GEN-END:variables

    private void genareteMemberID() {
        try {
            ResultSet rs = db.serch("select count(employee_id) as x from employee");
            if(rs.next()){
                String counts = rs.getString("x");
                
                int count = Integer.parseInt(counts);
               ++count;
                if(count<10){
                txtSearch.setText("E000"+count);
               // txtmi.setEditable(false);
                }else if(count<100){
                 txtSearch.setText("E00"+count);
               // txtmi.setEditable(false);
                }else if(count<1000){
                    txtSearch.setText("E0"+count);
                //txtmi.setEditable(false);
                }else if(count<10000){
                    txtSearch.setText("E"+count);
               // txtmi.setEditable(false);
                }
                  txtnic.grabFocus();
            }
           
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void seachem() {
         
        try {
     ResultSet rs = db.serch("select * from employee where employee_id='"+txtSearch.getText()+"'");
            stop=true;
            //bc.setVisible(true);
            //bu.setVisible(true);
         DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
         dtm.setRowCount(0);
         while(rs.next()){
            String name =rs.getString("first_name")+" "+rs.getString("last_name");
              String adress =rs.getString("ad_l1")+","+rs.getString("ad_l2")+","+rs.getString("ad_l3")+"."+("");
         Vector v =new Vector ();
         v.add(rs.getString("employee_id"));
         v.add(rs.getString("nic"));
          v.add(name);
            v.add(rs.getString("dob"));
              v.add(adress);
            v.add(rs.getString("contact"));
             v.add(rs.getString("register_date"));
            dtm.addRow(v);
                
         }
        // txtSearch.setText(null);
        } catch (Exception e) {
            e.printStackTrace();
        }
         
    }

    private void Loadmember() {
         try {
            ResultSet rs = db.serch("select * from employee where stat =1");
            DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
             while(rs.next()){
            String name =rs.getString("first_name")+" "+rs.getString("last_name");
              String adress =rs.getString("ad_l1")+","+rs.getString("ad_l2")+","+rs.getString("ad_l3")+"."+("");
         Vector v =new Vector ();
         v.add(rs.getString("employee_id"));
         v.add(rs.getString("nic"));
          v.add(name);
            v.add(rs.getString("dob"));
              v.add(adress);
            v.add(rs.getString("contact"));
             v.add(rs.getString("register_date"));
            dtm.addRow(v);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadText() {
       try{
            
              if(stop){
        DefaultTableModel df =(DefaultTableModel)jTable1.getModel();
       Vector v = new Vector();
       for(int x = 0;x<jTable1.getColumnCount();x++){
       String s = df.getValueAt(jTable1.getSelectedRow(), x).toString();
       v.add(s);
       }
       
      txtSearch.setText(v.get(0).toString());
      txtnic.setText(v.get(1).toString());
      String name=v.get(2).toString();
      txtfname.setText(name.split(" ")[0]);
      txtlname.setText(name.split(" ")[1]);
      String dob =v.get(3).toString();
               System.out.println(dob);
      SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
      Date date =sdf.parse(dob);
      caledob.setDate(date);
      String adress=v.get(4).toString();
      txtad1.setText(adress.split(",")[0]);
      txtad2.setText(adress.split(",")[1]);
      txtad3.setText(adress.split(",")[2]);
      txtcno.setText(v.get(5).toString());
      
              }
       }catch(Exception e){}
    }

    private void loadText2() {
        try {
            ResultSet serch = db.serch("SELECT * FROM employee WHERE employee_id='"+txtSearch.getText().toUpperCase()+"'");
            if(serch.next()){
           txtfname.setText(serch.getString("first_name"));
           txtlname.setText(serch.getString("last_name"));
           txtad1.setText(serch.getString("ad_l1"));
           txtad2.setText(serch.getString("ad_l2"));
           txtad3.setText(serch.getString("ad_l3"));
           txtnic.setText(serch.getString("nic"));
           txtcno.setText(serch.getString("contact"));
           caledob.setDate(serch.getDate("dob"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
