/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee;

import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import common.Checknull;
import common.TbView;
import common.db;
import finel_project_gamdora.main_menu;
import java.awt.Color;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author udesh
 */
public class Emplooye_register extends javax.swing.JFrame {

    /**
     * Creates new form Emplooye_register
     */
    public Emplooye_register() {
        initComponents();
         screensize();
        TbView.tableSettings(jTable1);        
         Loadmember();
         genareteMemberID();
    }
     boolean  textInput=false;
 private void screensize() {
      
    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel16 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnup2 = new javax.swing.JButton();
        txtemid = new javax.swing.JTextField();
        btnup = new javax.swing.JButton();
        btndash = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtad2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtcno = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        txtad3 = new javax.swing.JTextField();
        txtad1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        caledob = new com.toedter.calendar.JDateChooser();
        txtfname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnup1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1840, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 98, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("  Gamdora Distriburtors");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Employee ID");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 80, 130, 30));

        btnup2.setBackground(new java.awt.Color(0, 0, 51));
        btnup2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnup2.setForeground(new java.awt.Color(255, 255, 255));
        btnup2.setText(" Remove");
        btnup2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnup2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnup2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnup2MouseExited(evt);
            }
        });
        btnup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnup2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 250, 30));

        txtemid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtemid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemidActionPerformed(evt);
            }
        });
        getContentPane().add(txtemid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 80, 240, 30));

        btnup.setBackground(new java.awt.Color(0, 0, 51));
        btnup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnup.setForeground(new java.awt.Color(255, 255, 255));
        btnup.setText(" Update");
        btnup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnupMouseExited(evt);
            }
        });
        btnup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupActionPerformed(evt);
            }
        });
        getContentPane().add(btnup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, 30));

        btndash.setBackground(new java.awt.Color(0, 0, 51));
        btndash.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndash.setForeground(new java.awt.Color(255, 255, 255));
        btndash.setText("Back");
        btndash.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btndash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndashMouseExited(evt);
            }
        });
        btndash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndashActionPerformed(evt);
            }
        });
        getContentPane().add(btndash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 250, 30));

        jLabel3.setBackground(new java.awt.Color(0, 102, 0));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 60));

        jLabel4.setBackground(new java.awt.Color(0, 0, 51));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("  Emplooye Register");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 1050, 70));

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("setting");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 70, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 51));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 1220));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Last Name");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 130, 30));

        txtnic.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtnic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnicMouseClicked(evt);
            }
        });
        txtnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnicActionPerformed(evt);
            }
        });
        txtnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnicKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnicKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnicKeyTyped(evt);
            }
        });
        getContentPane().add(txtnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 240, 30));

        txtlname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });
        txtlname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlnameKeyTyped(evt);
            }
        });
        getContentPane().add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 240, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("DOB");
        jLabel21.setToolTipText("");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 150, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("L3.");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 50, 30));

        txtad2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtad2ActionPerformed(evt);
            }
        });
        txtad2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtad2KeyTyped(evt);
            }
        });
        getContentPane().add(txtad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 240, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Contact NO");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 150, 30));

        txtcno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtcno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnoActionPerformed(evt);
            }
        });
        txtcno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcnoKeyTyped(evt);
            }
        });
        getContentPane().add(txtcno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 240, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("First Name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 150, 30));

        jButton8.setBackground(new java.awt.Color(0, 0, 102));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Submit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 530, 180, 30));

        txtad3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtad3ActionPerformed(evt);
            }
        });
        txtad3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtad3KeyTyped(evt);
            }
        });
        getContentPane().add(txtad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 240, 30));

        txtad1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtad1ActionPerformed(evt);
            }
        });
        txtad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtad1KeyTyped(evt);
            }
        });
        getContentPane().add(txtad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 240, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("Address");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 120, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("L1.");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 50, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("L2.");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 50, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("NIC");
        jLabel23.setToolTipText("");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 150, 30));

        caledob.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(caledob, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 240, 30));

        txtfname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        txtfname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfnameKeyTyped(evt);
            }
        });
        getContentPane().add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 240, 30));

        jTable1.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee_id", "NIC", "Name", "DOB", "Address", "Contact", "Register_date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 660, 360));

        btnup1.setBackground(new java.awt.Color(0, 0, 51));
        btnup1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnup1.setForeground(new java.awt.Color(255, 255, 255));
        btnup1.setText(" Update");
        btnup1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnup1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnup1MouseExited(evt);
            }
        });
        btnup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnup1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 250, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashMouseEntered
        btndash.setBackground(Color.BLUE);
    }//GEN-LAST:event_btndashMouseEntered

    private void btndashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndashMouseExited
        btndash.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_btndashMouseExited

    private void btndashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndashActionPerformed
         new main_menu().setVisible(true);
    }//GEN-LAST:event_btndashActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnicActionPerformed
         Checknull.checkNull(txtnic, "nic", txtlname);
    }//GEN-LAST:event_txtnicActionPerformed

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
        Checknull.checkNull(txtlname, "lname", txtlname);
    }//GEN-LAST:event_txtlnameActionPerformed

    private void txtad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtad2ActionPerformed
        Checknull.checkNull(txtad2, "add2", txtad3);
    }//GEN-LAST:event_txtad2ActionPerformed

    private void txtcnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnoActionPerformed
      Checknull.checkNull(txtcno, "contact", txtcno);
      jButton8.grabFocus();
    }//GEN-LAST:event_txtcnoActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       try {
              Testtxt();
               if(textInput){
             String employeeId = txtemid.getText().toUpperCase();
             String nic= txtnic.getText().toUpperCase();
            String firstName= txtfname.getText().toUpperCase();
            String lastName= txtlname.getText().toUpperCase();
           Date dob= caledob.getDate();
           SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
           String adL1= txtad1.getText().toUpperCase();
           String adL2= txtad2.getText().toUpperCase();
           String adL3= txtad3.getText().toUpperCase();
            String contact =txtcno.getText().toUpperCase();
           String registerDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
            db.iud("insert into employee values('"+employeeId+"','"+nic+"','"+firstName+"','"+lastName+"','"+sdf.format(dob)+"','"+adL1+"','"+adL2+"','"+adL3+"','"+contact+"','"+registerDate+"','"+1+"')");
           
            JOptionPane.showMessageDialog(this,""+txtemid.getText()+"Employee is register");
            textInput=true;
            txtemid.setText(null);
           txtnic.setText(null);
           txtfname.setText(null);
           txtlname.setText(null);
           caledob.setDate(null);
           txtad1.setText(null);
           txtad2.setText(null);
           txtad3.setText(null);
           txtcno.setText(null);
             
             
             
            genareteMemberID();
              
      
      ResultSet rs = db.serch("select * from employee");
         DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
         dtm.setRowCount(0);
         while(rs.next()){
            String name =rs.getString("first_name")+" "+rs.getString("last_name");
              String adress =rs.getString("ad_l1")+","+rs.getString("ad_l2")+","+rs.getString("ad_l3");
         Vector v =new Vector ();
         v.add(rs.getString("employee_id"));
         v.add(rs.getString("nic"));
          v.add(name);
            v.add(rs.getString("dob"));
              v.add(adress);
            v.add(rs.getString("contact"));
             v.add(rs.getString("register_date"));
            dtm.addRow(v);
         
         
         }
               }
        
        }catch (NullPointerException n){
          JOptionPane.showMessageDialog(this, "Please  Fill Text Files");
        
        }catch(Exception e){
                e.printStackTrace();
        }
          
           
         
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtad3ActionPerformed
      Checknull.checkNull(txtad3, "add3", txtcno);
    }//GEN-LAST:event_txtad3ActionPerformed

    private void txtad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtad1ActionPerformed
        Checknull.checkNull(txtad1, "add1", txtad2);
    }//GEN-LAST:event_txtad1ActionPerformed

    private void btnupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupMouseEntered
       btnup.setBackground(Color.BLUE);
    }//GEN-LAST:event_btnupMouseEntered

    private void btnupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnupMouseExited
        btnup.setBackground(new Color(0,0,51));
    }//GEN-LAST:event_btnupMouseExited

    private void btnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupActionPerformed
        new EM_up().setVisible(true);
    }//GEN-LAST:event_btnupActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
         Checknull.checkNull(txtfname, "fname", txtlname);
    }//GEN-LAST:event_txtfnameActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
       

    }//GEN-LAST:event_jTable1MousePressed

    private void txtemidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemidActionPerformed

    private void btnup1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnup1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnup1MouseEntered

    private void btnup1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnup1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnup1MouseExited

    private void btnup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnup1ActionPerformed

    private void btnup2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnup2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnup2MouseEntered

    private void btnup2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnup2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnup2MouseExited

    private void btnup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnup2ActionPerformed
         new em_delete().setVisible(true);
    }//GEN-LAST:event_btnup2ActionPerformed

    private void txtnicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnicKeyTyped
        if(txtnic.getText().length()==12){
          evt.consume();
       }
    }//GEN-LAST:event_txtnicKeyTyped

    private void txtfnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfnameKeyTyped
          char keychar =evt.getKeyChar();
        boolean isDigit = Character.isDigit(keychar);
        if(isDigit){
        evt.consume();
        }
    }//GEN-LAST:event_txtfnameKeyTyped

    private void txtlnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlnameKeyTyped
       char keychar =evt.getKeyChar();
        boolean isDigit = Character.isDigit(keychar);
        if(isDigit){
        evt.consume();
        }
    }//GEN-LAST:event_txtlnameKeyTyped

    private void txtad2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtad2KeyTyped
         char keychar =evt.getKeyChar();
        boolean isDigit = Character.isDigit(keychar);
        if(isDigit){
        evt.consume();
        }
    }//GEN-LAST:event_txtad2KeyTyped

    private void txtad3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtad3KeyTyped
          char keychar =evt.getKeyChar();
        boolean isDigit = Character.isDigit(keychar);
        if(isDigit){
        evt.consume();
        }
    }//GEN-LAST:event_txtad3KeyTyped

    private void txtcnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnoKeyTyped
        if(txtcno.getText().length()==10){
          evt.consume();
         }
        
        if(!Character.isDigit(evt.getKeyChar())){
        evt.consume();
               // JOptionPane.showMessageDialog(this, "Sorry your enter string type");
        }
    }//GEN-LAST:event_txtcnoKeyTyped

    private void txtad1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtad1KeyTyped
       if(!Character.isDigit(evt.getKeyChar())){
        evt.consume();
               // JOptionPane.showMessageDialog(this, "Sorry your enter string type");
        }
    }//GEN-LAST:event_txtad1KeyTyped

    private void txtnicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnicKeyReleased
     if(txtnic.getText().length()==9){
              txtnic.setText(txtnic.getText().concat("V"));
            }else
              if(txtnic.getText().contains("V")||txtnic.getText().length()!=10){
             txtnic.setText(txtnic.getText().replace("V", ""));
          }
         if(txtnic.getText().length()==12){
                txtnic.setEditable(false);
                  }

    }//GEN-LAST:event_txtnicKeyReleased

    private void txtnicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnicKeyPressed
        if(evt.getKeyCode()==8){
       txtnic.setEditable(true);
       }

    }//GEN-LAST:event_txtnicKeyPressed

    private void txtnicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnicMouseClicked
       txtnic.setEditable(true);

    }//GEN-LAST:event_txtnicMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
          UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emplooye_register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndash;
    private javax.swing.JButton btnup;
    private javax.swing.JButton btnup1;
    private javax.swing.JButton btnup2;
    private com.toedter.calendar.JDateChooser caledob;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtad1;
    private javax.swing.JTextField txtad2;
    private javax.swing.JTextField txtad3;
    private javax.swing.JTextField txtcno;
    private javax.swing.JTextField txtemid;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtnic;
    // End of variables declaration//GEN-END:variables

    private void Testtxt() {
         if(!txtnic.getText().trim().equals("")){
        if(!txtlname.getText().trim().equals("")){
            if(!txtcno.getText().trim().equals("")){
                if(!txtad1.getText().trim().equals("")){
                    textInput=true;
                }else{
                 JOptionPane.showMessageDialog(this,"Please Enter your Address", "Address", 2);
                 textInput=false;
                }
            }else{
             JOptionPane.showMessageDialog(this,"Please Enter your Tel Number", "Phone Number", 2);
               textInput=false;
            }
        }else{
             JOptionPane.showMessageDialog(this,"Please Enter your Name", " Name", 2);
           textInput=false;
        }
    }else{
         JOptionPane.showMessageDialog(this,"Please Enter your NIC Number", "NIC", 2);
       textInput=false;
    }
    }

    private void genareteMemberID() {
         try {
            ResultSet rs = db.serch("select count(employee_id) as x from employee");
            if(rs.next()){
                String counts = rs.getString("x");
                
                int count = Integer.parseInt(counts);
               ++count;
                if(count<10){
                txtemid.setText("E000"+count);
               // txtmi.setEditable(false);
                }else if(count<100){
                 txtemid.setText("E00"+count);
               // txtmi.setEditable(false);
                }else if(count<1000){
                    txtemid.setText("E0"+count);
                //txtmi.setEditable(false);
                }else if(count<10000){
                    txtemid.setText("E"+count);
               // txtmi.setEditable(false);
                }
                  txtnic.grabFocus();
            }
           
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void Loadmember() {
         try {
            ResultSet rs = db.serch("select * from employee where stat =1");
            DefaultTableModel dtm =(DefaultTableModel)jTable1.getModel();
            dtm.setRowCount(0);
             while(rs.next()){
            String name =rs.getString("first_name")+" "+rs.getString("last_name");
              String adress =rs.getString("ad_l1")+","+rs.getString("ad_l2")+","+rs.getString("ad_l3")+"."+("");
         Vector v =new Vector ();
         v.add(rs.getString("employee_id"));
         v.add(rs.getString("nic"));
          v.add(name);
            v.add(rs.getString("dob"));
              v.add(adress);
            v.add(rs.getString("contact"));
             v.add(rs.getString("register_date"));
            dtm.addRow(v);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}

    

